---
- name: Connectivity test
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false

  tasks:
    - name: Change the hostname to { _hostname }
      ansible.windows.win_hostname:
      name: { _hostname }
      register: res
    
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
