---
- name: PowerShell Script
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false
  vars:
    remote_zip: "C:\\script.zip"
    remote_dest: "C:\\query_services.ps1"
    remote_folder: "C:"

  tasks:    
    - name: Copy zip to remote
      ansible.windows.win_copy:
        src: "{{ playbook_dir }}/script.zip"
        dest: "{{ remote_zip }}"
    
    - name: Unzip script.zip
      community.windows.win_unzip:
        src: "{{ remote_zip }}"
        dest: "{{ remote_folder }}"

    - name: Run Script
      ansible.windows.win_powershell:
        script: |
          {{ remote_dest }} -ServiceState {{ service_state }}
      register: ps_output

    - name: Print output
      ansible.builtin.debug:
        var: ps_output
